package com.mathworks.headcount.api.tests;

public class UpdateICReqReportstoToReqTest {
  /**
   * https://inside-apps-stage.mathworks.com/headcount/api/v1/headcounts?phase=plan
   * 201
   *
   *
   * {"info":"","editAllowed":true,"orgNode":"5BE385BA62F0","orgNodeString":"/1/3/5/4/2/56/3/","orgLevel":7,"nodeId":"REQ_22807","name":"PROPOSED 2142","nameLong":"PROPOSED 2142","managedSupervisoryOrgId":null,"managedSupervisoryOrgName":null,"type":"REQ","id":22807,"reqType":{"id":35,"name":"Budgeted"},"jobCodeName":"Quality Engineer ","reportsTo":{"type":"REQ","id":"22806","name":"PROPOSED 2143"},"supervisoryOrg":{"label":"Manages PROPOSED 2143:34-13-20 14:34 (PROPOSED 2143, SUP_PROP_103)","value":"SUP_PROP_103","parentSupervisoryOrgId":"SUP_PROP_102","managerId":22806,"managerName":"PROPOSED 2143","managerType":"REQ","id":"SUP_PROP_103","name":"Manages PROPOSED 2143:34-13-20 14:34","planData":true},"department":{"deptId":"1510","name":"Quality Engineering"},"location":{"id":19,"name":"US-Natick","nameRollup":"US-Natick","country":"US","eligibilityRule":"Country - US"},"jobCode":"QUE20I","jobLevel":"I2","status":{"id":1,"name":"Unopened"},"isManager":"N","regTemp":"REG","termDate":null,"reqLatestActivity":null,"reqRecruiter":"Brian Hill","reqDaysActive":null,"totalReports":null,"directReports":null,"totalReqs":null,"totalAdds":null,"totalVpRequested":null,"totalVpDeferred":null,"totalVpOther":null,"ancestorsPath":"SUP_2590,SUP_PROP_102,REQ_22807","ancestors":["SUP_MATHWORKS","SUP_195","SUP_172","SUP_462","SUP_927","SUP_2590","SUP_PROP_102","SUP_PROP_103","REQ_22807"],"justification":null,"planData":false,"confidentialNotes":null,"hasChanges":"Y","userField1":null,"userField2":null,"userField3":null,"userField4":null,"mgrPriority":null,"directorPriority":null,"srDirectorPriority":null,"vpPriority":null,"directorProposedReviewStatus":null,"srDirectorProposedReviewStatus":null,"vpProposedReviewStatus":null,"budgetApprovalStatus":"Unreviewed","budgetApprovalComments":null,"vp":{"type":"staff","id":172,"name":"Josh Tillotson"},"productGroup":null,"productGroupImportedName":null,"salesTerritories":null,"salesTerritoryTypes":null,"comments":null,"roleDesc":null,"geckoComponent":{"id":null,"name":null},"changesCurrentToPlan":"Manager: Jessica Fairbanks (2590, STAFF) to PROPOSED 2141 (2141, PROPOSED)","headcountCurrentFieldsModel":{"mgrCurrent":false,"jobCodeCurrent":"QUE20I","deptIdCurrent":"1510","deptNameCurrent":"Quality Engineering","locationIdCurrent":19,"locationNameCurrent":null,"supervisoryOrgIdCurrent":"SUP_PROP_102","supervisoryOrgNameCurrent":"Manages PROPOSED 2141:13-01-20 14:33","reportsToIdCurrent":2590,"reportsToTypeCurrent":"STAFF","reportsToNameCurrent":"Jessica Fairbanks"},"proposedId":2142,"reqOriginType":"Proposed","reqOriginYear":2020}
   */
}
